// Order
export const FETCH_ORDER = 'FETCH_ORDER'
export const FETCH_ORDER_PENDING = 'FETCH_ORDER_PENDING'
export const FETCH_ORDER_FULFILLED = 'FETCH_ORDER_FULFILLED'
export const FETCH_ORDER_REJECTED = 'FETCH_ORDER_REJECTED'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const UPDATE_ORDER_PENDING = 'UPDATE_ORDER_PENDING'
export const UPDATE_ORDER_FULFILLED = 'UPDATE_ORDER_FULFILLED'
export const UPDATE_ORDER_REJECTED = 'UPDATE_ORDER_REJECTED'
export const UPDATE_ORDER_OPTIMISTICALLY = 'UPDATE_ORDER_OPTIMISTICALLY'

// Snackbar
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR'
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'
